### ISSUE TITLE
Machine Learning Interpretability - White-Box Models Feedback

### ISSUE THREAD

**Issue by scarlettvalentin** [learn-co-curriculum/dsc-ml-interp-whitebox-models#1]
## Link to Canvas

https://learning.flatironschool.com/courses/7301/pages/machine-learning-interpretability-white-box-models?module_item_id=651782

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x ] Other (explain below)

### Source

```
This lesson should have come before the Quiz: ML Interpretability 1, as the questions to that quiz were answered in this lesson. 
```

## What OS Are You Using?

- [x ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for raising this issue. We'll take a look.

**Comment by bpurdy-ds** [comment]
Updated. Thanks.
